apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: bal-service-endpoint
      port: 9090
      type: REST
      networkVisibility: Public
      context: /
      schemaFilePath: ""
